# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73f78f4ecdf7b83b249747f17bf7bc1e3e27564f2230336c29c86f9340e12e9acefc653f2bfc6bafa9516dc94978d2d31a473750549315fa1fe7528bfaadc041

test:
  secret_key_base: 45a3c468bd137aa033997624f84ef2c57bf9716bf9b3323c2c12b3245353cabd09f8d7d18f926fc7a0b25f65aed3e0dfb08d5adb533a82aac9cc5b094858b5ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
